include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, "**/*.g.dart"]

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    require_trailing_commas: true
