targets:
  $default:
    builders:
      # hive_ce_generator|hive_schema_migrator:
      #   enabled: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - require_trailing_commas
            - unnecessary_breaks
