targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - require_trailing_commas
            - unnecessary_breaks
            - invalid_use_of_protected_member
