// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore_for_file: require_trailing_commas, unnecessary_breaks, invalid_use_of_protected_member

import 'package:hive_ce/hive.dart';
import 'package:hds_overlay/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChartWidgetPropertiesAdapter());
    registerAdapter(DataTypeAdapter());
    registerAdapter(DataWidgetPropertiesAdapter());
    registerAdapter(FirebaseConfigAdapter());
    registerAdapter(OverlayProfileAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(Tuple2DoubleAdapter());
  }
}
